export interface BacklinkSource {
  id: string;
  name: string;
  platform_type: string;
  base_url: string;
  search_url_template: string;
  verify_url_pattern: string;
  is_active: boolean;
  logo_icon: string;
  color: string;
  sort_order: number;
}

export const TARGET_DOMAIN = "immaculate.tr";

export const SOURCES: BacklinkSource[] = [
  { id: "wikipedia-en", name: "Wikipedia (EN)", platform_type: "wiki", base_url: "https://en.wikipedia.org", search_url_template: "https://en.wikipedia.org/w/index.php?search={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "BookOpen", color: "#000000", sort_order: 1 },
  { id: "wikipedia-tr", name: "Wikipedia (TR)", platform_type: "wiki", base_url: "https://tr.wikipedia.org", search_url_template: "https://tr.wikipedia.org/w/index.php?search={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "BookOpen", color: "#D4392E", sort_order: 2 },
  { id: "wikimedia-commons", name: "Wikimedia Commons", platform_type: "wiki", base_url: "https://commons.wikimedia.org", search_url_template: "https://commons.wikimedia.org/w/index.php?search={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Image", color: "#0066CC", sort_order: 3 },
  { id: "wikidata", name: "Wikidata", platform_type: "wiki", base_url: "https://www.wikidata.org", search_url_template: "https://www.wikidata.org/w/index.php?search={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Database", color: "#000000", sort_order: 4 },
  { id: "wiktionary", name: "Wiktionary", platform_type: "wiki", base_url: "https://en.wiktionary.org", search_url_template: "https://en.wiktionary.org/w/index.php?search={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "BookOpen", color: "#4A4A4A", sort_order: 5 },
  { id: "wikiquote", name: "Wikiquote", platform_type: "wiki", base_url: "https://en.wikiquote.org", search_url_template: "https://en.wikiquote.org/w/index.php?search={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "BookOpen", color: "#665A3E", sort_order: 6 },
  { id: "wikibooks", name: "Wikibooks", platform_type: "wiki", base_url: "https://en.wikibooks.org", search_url_template: "https://en.wikibooks.org/w/index.php?search={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "BookOpen", color: "#5C7A99", sort_order: 7 },
  { id: "wikisource", name: "Wikisource", platform_type: "wiki", base_url: "https://en.wikisource.org", search_url_template: "https://en.wikisource.org/w/index.php?search={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "BookOpen", color: "#436F82", sort_order: 8 },
  { id: "github", name: "GitHub", platform_type: "social", base_url: "https://github.com", search_url_template: "https://github.com/search?q={query}&type=code", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Github", color: "#181717", sort_order: 10 },
  { id: "gitlab", name: "GitLab", platform_type: "social", base_url: "https://gitlab.com", search_url_template: "https://gitlab.com/search?search={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "GitBranch", color: "#FC6D26", sort_order: 11 },
  { id: "codeberg", name: "Codeberg", platform_type: "social", base_url: "https://codeberg.org", search_url_template: "https://codeberg.org/explore/repos?q={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "GitBranch", color: "#2185D0", sort_order: 12 },
  { id: "sourcehut", name: "SourceHut", platform_type: "social", base_url: "https://sr.ht", search_url_template: "https://sr.ht/projects?search={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "GitBranch", color: "#000000", sort_order: 13 },
  { id: "bitbucket", name: "Bitbucket", platform_type: "social", base_url: "https://bitbucket.org", search_url_template: "https://bitbucket.org/search?q={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "GitBranch", color: "#0052CC", sort_order: 14 },
  { id: "gitea", name: "Gitea", platform_type: "social", base_url: "https://gitea.com", search_url_template: "https://gitea.com/explore/repos?q={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "GitBranch", color: "#609926", sort_order: 15 },
  { id: "reddit", name: "Reddit", platform_type: "social", base_url: "https://www.reddit.com", search_url_template: "https://www.reddit.com/search/.json?q={query}&limit=25", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "MessageCircle", color: "#FF4500", sort_order: 20 },
  { id: "hackernews", name: "Hacker News", platform_type: "social", base_url: "https://news.ycombinator.com", search_url_template: "https://hn.algolia.com/api/v1/search?query={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Newspaper", color: "#FF6600", sort_order: 21 },
  { id: "lobsters", name: "Lobsters", platform_type: "social", base_url: "https://lobste.rs", search_url_template: "https://lobste.rs/search.json?q={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Newspaper", color: "#AC130D", sort_order: 22 },
  { id: "slashdot", name: "Slashdot", platform_type: "social", base_url: "https://slashdot.org", search_url_template: "https://slashdot.org/search?query={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Newspaper", color: "#026664", sort_order: 23 },
  { id: "stackoverflow", name: "Stack Overflow", platform_type: "qa", base_url: "https://stackoverflow.com", search_url_template: "https://api.stackexchange.com/2.3/search/advanced?q={query}&site=stackoverflow&pagesize=25&order=desc&sort=relevance&filter=withbody", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "HelpCircle", color: "#F48024", sort_order: 30 },
  { id: "stackexchange", name: "Stack Exchange", platform_type: "qa", base_url: "https://stackexchange.com", search_url_template: "https://api.stackexchange.com/2.3/search/advanced?q={query}&site=serverfault&pagesize=10&order=desc&sort=relevance", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "HelpCircle", color: "#37A6CE", sort_order: 31 },
  { id: "superuser", name: "Super User", platform_type: "qa", base_url: "https://superuser.com", search_url_template: "https://api.stackexchange.com/2.3/search/advanced?q={query}&site=superuser&pagesize=10&order=desc&sort=relevance", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "HelpCircle", color: "#47A8DA", sort_order: 32 },
  { id: "askubuntu", name: "Ask Ubuntu", platform_type: "qa", base_url: "https://askubuntu.com", search_url_template: "https://api.stackexchange.com/2.3/search/advanced?q={query}&site=askubuntu&pagesize=10&order=desc&sort=relevance", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "HelpCircle", color: "#DD4814", sort_order: 33 },
  { id: "quora", name: "Quora", platform_type: "qa", base_url: "https://www.quora.com", search_url_template: "https://www.quora.com/search?q={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "HelpCircle", color: "#B92B27", sort_order: 34 },
  { id: "devto", name: "Dev.to", platform_type: "social", base_url: "https://dev.to", search_url_template: "https://dev.to/search/feed?q={query}&per_page=30", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Code", color: "#0A0A0A", sort_order: 40 },
  { id: "medium", name: "Medium", platform_type: "social", base_url: "https://medium.com", search_url_template: "https://medium.com/search?q={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "PenTool", color: "#12100E", sort_order: 41 },
  { id: "hashnode", name: "Hashnode", platform_type: "social", base_url: "https://hashnode.com", search_url_template: "https://hashnode.com/search?q={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Code", color: "#2962FF", sort_order: 42 },
  { id: "hackernews2", name: "Lobsters RSS", platform_type: "social", base_url: "https://lobste.rs", search_url_template: "https://lobste.rs/rss", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Newspaper", color: "#AC130D", sort_order: 43 },
  { id: "duckduckgo", name: "DuckDuckGo", platform_type: "search", base_url: "https://duckduckgo.com", search_url_template: "https://html.duckduckgo.com/html/?q={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Search", color: "#DE5833", sort_order: 50 },
  { id: "bing", name: "Bing", platform_type: "search", base_url: "https://www.bing.com", search_url_template: "https://www.bing.com/search?q={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Search", color: "#008373", sort_order: 51 },
  { id: "yandex", name: "Yandex", platform_type: "search", base_url: "https://yandex.com", search_url_template: "https://yandex.com/search/?text={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Search", color: "#FF0000", sort_order: 52 },
  { id: "startpage", name: "Startpage", platform_type: "search", base_url: "https://www.startpage.com", search_url_template: "https://www.startpage.com/sp/search?query={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Search", color: "#6C5CE7", sort_order: 53 },
  { id: "archive-org", name: "Internet Archive", platform_type: "archive", base_url: "https://archive.org", search_url_template: "https://archive.org/advancedsearch.php?q={query}&fl[]=identifier&fl[]=title&fl[]=url&rows=25&output=json", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Archive", color: "#000000", sort_order: 60 },
  { id: "archive-today", name: "archive.today", platform_type: "archive", base_url: "https://archive.ph", search_url_template: "https://archive.ph/{query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Archive", color: "#0E0E0E", sort_order: 61 },
  { id: "openstreetmap", name: "OpenStreetMap", platform_type: "directory", base_url: "https://www.openstreetmap.org", search_url_template: "https://www.openstreetmap.org/api/0.6/search?q={query}&format=json", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Globe", color: "#7EBC6F", sort_order: 70 },
  { id: "crates-io", name: "crates.io", platform_type: "directory", base_url: "https://crates.io", search_url_template: "https://crates.io/api/v1/crates?q={query}&per_page=10", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Package", color: "#8B5CF6", sort_order: 71 },
  { id: "npm", name: "npm", platform_type: "directory", base_url: "https://www.npmjs.com", search_url_template: "https://registry.npmjs.org/-/v1/search?text={query}&size=25", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Package", color: "#CB3837", sort_order: 72 },
  { id: "pypi", name: "PyPI", platform_type: "directory", base_url: "https://pypi.org", search_url_template: "https://pypi.org/search/?q={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Package", color: "#3775A9", sort_order: 73 },
  { id: "rubygems", name: "RubyGems", platform_type: "directory", base_url: "https://rubygems.org", search_url_template: "https://rubygems.org/api/v1/search.json?query={query}", verify_url_pattern: "immaculate\\.tr", is_active: true, logo_icon: "Package", color: "#E9573F", sort_order: 74 },
];
